### ISSUE TITLE
Is it possible to show in "Markdown preview enhanced"?

### ISSUE THREAD

**Issue by martintang** [phoihos/vscode-markdown-markmap#2]
It seems this extensions can only work on original markdown preview, 
It's better this can work on markdown preview enhanced.
Thanks.

**Comment by phoihos** [comment]
[Author of "vscode-markdown-tinymind" says](https://github.com/ArcticLampyrid/vscode-markdown-tinymind/issues/1#issuecomment-619006634
):
> Markdown Preview Enhanced has its own engine called [shd101wyy/mume](https://github.com/shd101wyy/mume), it packaged markdown-it but did not have api to add any extensions.
> The only way to add a extension is to fork it and hardcode the extension.
> https://github.com/shd101wyy/mume/blob/cb0dfce15e0a937be7bbfd4fb62ee33d28b2c2b0/src/markdown-engine.ts#L252

Related issue: https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/340

**Comment by martintang** [comment]
Ok, got it.
Thanks!
