### ISSUE TITLE
Export function

### ISSUE THREAD

**Issue by JBlond** [phoihos/vscode-markdown-markmap#3]
It would be very nice, if it was possible to export the generated map.

**Comment by phoihos** [comment]
I used [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) extension to export markdown contents.
If you want to export **Markmap contents only**, you can use [Markmap](https://marketplace.visualstudio.com/items?itemName=gera2ld.markmap-vscode) extension.

**Comment by JBlond** [comment]
The Markmap extension exports some very ugly HTML with external JS and doesn't work locally.
The Markdown All in One doesn't export the Mindmap at all.

I would like to export the generated SVG.

**Comment by phoihos** [comment]
**Markdown All in One** could export with **Markmap contents** correctly, but not now.
I'll investigate it out.
Thank you for your reporting.

**Comment by phoihos** [comment]
I created PR to [**Markdown All in One** repo](https://github.com/yzhang-gh/vscode-markdown) to fix this export problem.
(PR : https://github.com/yzhang-gh/vscode-markdown/pull/956)

Please wait new **Markdown All in One** release version with my PR merged.

**Comment by JBlond** [comment]
With that patch I get a blank page or the area is very small to see the SVG.

Iisn't it an opton for you that us possible to export the SVG data generated fro, this plugin?

**Comment by phoihos** [comment]
Did you test the [dev build](https://github.com/yzhang-gh/vscode-markdown/actions/runs/873932957) with my PR merged?

The new version of **Markdown All in One** would be **v3.5.0**.
But that version hasn't been released yet, check it out the [Milestone](https://github.com/yzhang-gh/vscode-markdown/milestone/1).

**Comment by JBlond** [comment]
Yes, I used the last Dev Build https://github.com/yzhang-gh/vscode-markdown/suites/2821934120/artifacts/62842107

From the plugin ![size](https://user-images.githubusercontent.com/2391810/120926553-a7c96d80-c6dd-11eb-8015-3060738345db.png)

The area has a fixed size.
![size2](https://user-images.githubusercontent.com/2391810/120926725-65546080-c6de-11eb-93c3-5f597b8461bc.png)


In VSC with your plugin:
![size-orig](https://user-images.githubusercontent.com/2391810/120926614-f840cb00-c6dd-11eb-89af-57de82544126.png)

**Comment by JBlond** [comment]
Since your plugins already creates the SVG code. All I would like is to export the SVG data. Like

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
 version="1.1" baseProfile="full"
 width="700px" height="400px" viewBox="0 0 700 400">

 <!-- Anschlüsse links und rechts -->
 <line x1="0" y1="200" x2="700" y2="200" stroke="black" stroke-width="20px"/>
 <!-- Das Rechteck -->
 <rect x="100" y="100" width="500" height="200" fill="white" stroke="black" stroke-width="20px"/>
 <!-- Der Schleifer -->
 <line x1="180" y1="370" x2="500" y2="50" stroke="black" stroke-width="15px"/>
 <!-- Die Pfeilspitze -->
 <polygon points="585 0 525 25 585 50" transform="rotate(135 525 25)"/>
</svg>
```

**Comment by phoihos** [comment]
Could you upload the sample markmap contents?
Maybe i could add the feature adjust width&height styles.

**Comment by JBlond** [comment]
You can fetch it from this [gist](https://gist.githubusercontent.com/JBlond/14ee2bbab303ffe6a537ea8cc29b40d3/raw/5fcba659f28e5b661e2eba103a5749702c5eb850/sample.md)

**Comment by phoihos** [comment]
![markmap-result](https://user-images.githubusercontent.com/19480673/120990388-73c47a00-c7bb-11eb-87e4-115547f46887.png)
Above screenshot is from the **Markdown All in One** [**dev build**](https://github.com/yzhang-gh/vscode-markdown/actions/runs/873932957).
The size of markmap contents was correctly exported with **Markdown Preview Markmap Support** and **Markdown All in One**.

Did you install the any other Markdown extensions?

**Comment by JBlond** [comment]
I have only davidanson.vscode-markdownlint and phoihos/vscode-markdown-markmap installed for markdown

**Comment by JBlond** [comment]
![incpector](https://user-images.githubusercontent.com/2391810/120999087-026bd380-c789-11eb-934e-3dd4bdceb4dc.png)

As you can see, there aren't those style values for hight and width. I tried with a fresh install. The same result.

**Comment by JBlond** [comment]
I tried [markmap-cli](https://github.com/gera2ld/markmap/tree/master/packages/markmap-cli) and that creates a working mind map.
Even though I would prever a pure SVG outout.

**Comment by phoihos** [comment]
I tried export just with two extensions installed:
> ![markmap-ext](https://user-images.githubusercontent.com/19480673/121153674-39bdab80-c881-11eb-8ea5-92d5953d3b4d.png)
- **Markdown All in One** from the [dev build](https://github.com/yzhang-gh/vscode-markdown/actions/runs/873932957)
- **Markdown Preview Markmap Support** from the [market place](https://marketplace.visualstudio.com/items?itemName=phoihos.markdown-markmap)

Screenshot below is the result:
![markmap-result](https://user-images.githubusercontent.com/19480673/121153691-3d513280-c881-11eb-9a65-32ce50f94779.png)

Attachment below includes the markmap md file and exported html file:
[markmap.zip](https://github.com/phoihos/vscode-markdown-markmap/files/6614953/markmap.zip)

**Comment by JBlond** [comment]
The same result. With one exception. I always tried in firefox. Today I tried in Chrome and there is works flawless.

**Comment by JBlond** [comment]
Isn't the export function a variant of the existing https://github.com/phoihos/vscode-markdown-markmap/blob/master/src/markdownItMarkmap.ts#L18 ?

**Comment by phoihos** [comment]
No. Text content converts to pre-parsed svg object and pass to renderer.
Is any problem on https://github.com/phoihos/vscode-markdown-markmap/blob/master/src/markdownItMarkmap.ts#L18 ?

**Comment by JBlond** [comment]
No, there is no problem with that. I just thought that it might be an idea how to get the SVG code for the export.

**Comment by phoihos** [comment]
I thought that idea might be impossible.
Because SVG elements must be generated with the element size.
And calculation of the element size need CSS styles and Fonts (if include KaTeX).
But CSS styles and Fonts are loaded at render time not parsing time.

If you have a solution, please let me know 😄

**Comment by JBlond** [comment]
The rendering isn't a problem. The export would just need the XML Data from the SVG.

**Comment by JBlond** [comment]
The project that inspired you to create this plugin has here its export function https://github.com/dundalek/atom-markdown-mindmap/blob/master/spec/markdown-mindmap-view-spec.coffee#L163
Maybe that helps.

**Comment by phoihos** [comment]
Finally, the new version of **Markdown All in One** that includes [my PR](https://github.com/yzhang-gh/vscode-markdown/pull/956) has released.

Please update the [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) extension.
