### ISSUE TITLE
markmap support extension cause markdown code block Double fuzzy

### ISSUE THREAD

**Issue by heartacker** [phoihos/vscode-markdown-markmap#4]
Issue Type: <b>Bug</b>

Double fuzzy

Extension version: 1.2.3
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.67GB (1.31GB free)|
|Process Argv|--crash-reporter-id dda9faca-e42e-4975-a2ba-c96c78991221|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615:30325510

```

</details>

**Comment by heartacker** [comment]
- normal  darkmode
![image](https://user-images.githubusercontent.com/1876302/123380382-f32ab980-d5c1-11eb-8c2b-e9152cd8fac9.png)

- enable markmap support
![image](https://user-images.githubusercontent.com/1876302/123380490-181f2c80-d5c2-11eb-994f-5e67e0fa685d.png)


![image](https://user-images.githubusercontent.com/1876302/123380442-06d62000-d5c2-11eb-9323-c78d0ed0bd47.png)

**Comment by phoihos** [comment]
Could you let me know all extensions installed of your vscode?

**Comment by heartacker** [comment]
> Could you let me know all extensions installed of your vscode?

that's all about markdown

![image](https://user-images.githubusercontent.com/1876302/123506248-cd6ee480-d695-11eb-97f4-7b8b691423bb.png)

**Comment by phoihos** [comment]
Did you install the **Markdown Preview Markmap Support**?
I can't see it on your extension list.

**Comment by heartacker** [comment]
installed
I  just disable it.

pic just shows the others  Mark down extensions.

**Comment by phoihos** [comment]
Ok. Could you upload the sample markdown contents that occur the issue?

**Comment by heartacker** [comment]
hi， i found that when identified the language of code-chunk， the issue will reproduce.
![image](https://user-images.githubusercontent.com/1876302/123536527-4e44e380-d75d-11eb-8c1d-26fef006b096.png)

**Comment by JBlond** [comment]
I have the same issue. As soon I add any language behind the back ticks. Tried with

**Comment by phoihos** [comment]
I found the reason:
`prism.css` internally used for highligting code. The `prism.css` occured the double fuzzy issue.

I'll fix this issue soon.
Thank you for your reporting.

**Comment by phoihos** [comment]
This issue fixed in 1.3.0 version.
Plz. Update to latest **Markdown Preview Markmap Support** extension from [Marketplace](https://marketplace.visualstudio.com/items?itemName=phoihos.markdown-markmap).

Related commit: d2c4b6bc09509f3a8315062ff2879dac01ebd1da

**Comment by phoihos** [comment]
@heartacker, @JBlond
Thank you  again for your reporting.

**Comment by JBlond** [comment]
@phoihos Thank you. That fixed the issue.
