### ISSUE TITLE
Formula too short from example code

### ISSUE THREAD

**Issue by JBlond** [phoihos/vscode-markdown-markmap#5]
![formula_too_short](https://user-images.githubusercontent.com/2391810/124085259-2224ad80-da50-11eb-866a-255bbc7e2441.png)

The Formula after MathJax is not fully visible.

**Comment by phoihos** [comment]
I tested it:
![markmap_katex](https://user-images.githubusercontent.com/19480673/124087058-9c732300-da8c-11eb-8ed0-9bed22a1c79c.png)

Could you let me know installed extensions about markdown preview feature?

**Comment by JBlond** [comment]
I have tested that with all extensions disabled but this one. I still get the same result.

**Comment by phoihos** [comment]
My test is also has the issue:
Word `4ac` must be rendered. But word `4a` are being rendered.

I'll investigate this issue.
Thank you for your reporting.

**Comment by phoihos** [comment]
I fixed this issue and released new version on [Marketplace](https://marketplace.visualstudio.com/items?itemName=phoihos.markdown-markmap).

But I couldn't find a perfect solution.
So I solved the issue by adding an option `kpadr` for katex rendering.
I'll try to find the perfect solution when I have some free time.

Thank you again for your reporting.

**Comment by JBlond** [comment]
Thank you. That fixed it.
