### ISSUE TITLE
Local Link is redirected to https://77fa9930-2f12-4071-baaf-ebf10cd3fb87.vscode-webview-test.com/vscode-resource/

### ISSUE THREAD

**Issue by joness95** [phoihos/vscode-markdown-markmap#7]
If using local links in the Markdown, its redirected to the webview test of vs-code.

Neither using file:... nor code:... helps.

**Comment by phoihos** [comment]
Could you upload the sample markdown contents that occur the issue?

**Comment by phoihos** [comment]
This issue has been closed because there has been no response.
With only the information that is currently in the issue, i don't have enough information to take action.
Please reach out if you have or find the answers i need so that i can investigate further.
