### ISSUE TITLE
can not render in preview

### ISSUE THREAD

**Issue by HaibaraMegumi** [phoihos/vscode-markdown-markmap#8]
can not render in preview
![image](https://user-images.githubusercontent.com/60850531/183872213-133b5723-458b-4b0c-a33e-c9e36e5585bb.png)

**Comment by phoihos** [comment]
If you use a [Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced), check [this](https://github.com/phoihos/vscode-markdown-markmap/issues/2) issue.

**Comment by HaibaraMegumi** [comment]
Sorry, i dont how  to fork it and hardcode the extension and then option. Could you give some help, Thanks

**Comment by phoihos** [comment]
This issue is out the scope of this project.
I think it might be a good idea to ask to the [Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) for help.
Thanks.
